### ISSUE TITLE
FEAT: Use memtest86+ (or similar) to generate badmem map.

### ISSUE THREAD

**Issue by BrianCArnold** [0nelight/macOS-Disable-RAM-Areas#11]
Can we launch memtest86+ with parameters that cause it to generate the desired file, no user input necessary? 

If so, and if the EFI file for it and the output file are in a predictable path location (we should be able to provide an install utility to ensure this), we can then prompt the user and say "hey, I don't see a badmem.dat file, would you like to generate one?" and kick off the process.

Alternatively, can we also do the same tests/use code from memtest86+ to get the bad memory locations and generate the file that way?

**Comment by 0nelight** [comment]
Also had this Idea. But this would turn this tool from a simply patch-script-binary into a full fledged application with the surface area for bugs and maintainance would increase dramatically. As I am neither an low-level expert, nor an C-EFI dev and I have no special passion becoming one and maintaining this, I cannot help with this endeavor. Altough I think there a quite some people on the planet having the demand for disabeling RAM-Areas with EFI befor the OS boots, I don't think implementing all the stuff needed for making this a standalone tool is worth my time and people could simply boot memtest once, note the areas and run the tool. In case you want to implement a standalone version, please do it on your own fork :-)

**Comment by BrianCArnold** [comment]
Oh, I was actually planning on doing this on my own fork and opening a PR. However, if you'd prefer (once mine is working) for people to kind of "move over" to using mine, I'll manage work there. I just want people to know that this IS being worked on.
