### ISSUE TITLE
OS not booting with script attached, (Macbook Air Early 2015 - rEFInd)

### ISSUE THREAD

**Issue by VincePuc99** [0nelight/macOS-Disable-RAM-Areas#5]
In case you have general Questions please ask it in the [Q/A Section of Discussions](https://github.com/0nelight/macOS-Disable-RAM-Areas/discussions/categories/q-a)

**System**
Mac-Computer Model - MacBookAir 13'' Early 2015
MacOS System Version - Monterey 12.7.6
Firmware Version - 489.0.0.0.0
Bootmanager Version - rEFInd 0.14.2
disable-ram-area.efi Release-Version - v0.1.0-alpha

**Output of [Apple Diagnostic](https://support.apple.com/en-us/102550)**
PPM002 - There may be an issue with the onboard memory

**Output of memtest86+ in Error-Summary-Mode**
Several:
0x26380fff0      0x269610630
0x263810070   0x269610630
0x263810070   0x2696105b0

**Describe the bug**
rEFInd not booting when inserted RAM areas above, memory hole?

**Comment by VincePuc99** [comment]
I runned a memmap with EFI shell if this can help, here is the output file.
[output.txt](https://github.com/user-attachments/files/16961598/output.txt)

**Comment by 0nelight** [comment]
Thank you for providing everything in detail - also the memmap!

According to the memmap, the damaged area is in the "available" address space - so normally it should work.

At the moment I suspect there may be an incompatibility regarding your Firmware-Version 489.0.0.0.0.
On my system I have 478.0.0.0.0 so the hang maybe arises from this.

Because the EFI-Spec of Apple is not public we have to experiment a little bit. I will compile a different version with your specified area hardcoded in it so the code is as simple as possible and maybe sucessfully runs.

**Comment by VincePuc99** [comment]
Thank you too for your help! There is absolutely no problem, i will wait your instructions for booting with your new file!

**Comment by VincePuc99** [comment]
Yeah my bad, i probably didnt described my issue very well, basically after adding the config on rEFInd and launching the OS with your efi file (through rEFInd), the OS dont boot at all. Its stay stuck on the screen attached, not even return to rEFInd main page, for resetting i need to long press the power button than it boot to rEFInd main page and only then i can boot to the OS without the custom script. Im going to try your file right now! Thank You!
![366400313-304252b0-f854-43ff-a724-21c454d19ca5](https://github.com/user-attachments/assets/944027fe-9aad-4761-8535-58615e401b6b)

**Comment by VincePuc99** [comment]
Trying your script right now, it goes to rEFInd main page flawlessly, running a memtest right now, i will keep you updated! Thank you as always for your works!

**Comment by VincePuc99** [comment]
Just finished a memtest and i got all the errors of past tests, i have a new low address too: 0002638100f0 . The highest remain unchanged, do i need to boot your efi file on top of memtest? if yes can you tell me how to do it? I have memtest on an external drive

**Comment by VincePuc99** [comment]
Just finished memtest, i got all past errors, do i need to bind your efi to memtest?

**Comment by 0nelight** [comment]
The file which I gave you was compiled differently to avoid the hang, it seems there are more Issues here. I maybe have to switch EFI-Lib from "gnu-efi" to "titanocore". Still figuring out how to do that. Lets see if I have some time for the next weekends! Thanks for your patience :-)

**Comment by 0nelight** [comment]
Could you please run memtest again and check if the defective areas stay the same? Please update the first Issue-Post with the latest Values. 

Also I have to check: You made sure you executed the EFI-Program in the ZIP-File from above, directly after that, this EFI-Program exited back into rEFInd Bootmanager and then you switched to memtest to check? 

If your MacBook restarts then the changes made by the EFI-Program will be gone again, it has to be executed before every boot. 
Only want to make sure we are on the same page.

**Comment by VincePuc99** [comment]
Heres all steps as requested ;)

![IMG_0090](https://github.com/user-attachments/assets/55d55b4c-6b7b-472f-a462-1790655188fd)

![IMG_0089](https://github.com/user-attachments/assets/97862b49-1c41-4cf7-a691-ef5ba299b47f)

https://github.com/user-attachments/assets/5314b2b2-632a-4030-8221-dad7d66770b4

![IMG_0093](https://github.com/user-attachments/assets/fbdbfeaf-52a7-4a1a-b7b5-c5ecc4ed05ba)

**Comment by 0nelight** [comment]
Please test this (also best with pictures) :-) 
[testing-v2-for-vincepuc99.zip](https://github.com/user-attachments/files/16996238/testing-v2-for-vincepuc99.zip)

**Comment by VincePuc99** [comment]
![IMG_0098](https://github.com/user-attachments/assets/2a37c013-3684-48a0-b3f6-e2d0ab2de132)

**Comment by 0nelight** [comment]
Can you please make sure you are using the memtest64.efi from [here](https://www.memtest.org/download/v7.00/mt86plus_7.00.binaries.zip)? Don't use the memtest64plus ISO but the EFI so we can make sure that the Addresses reported from memtest86+ get the same memory map.

**Comment by VincePuc99** [comment]
Absolutely, give me a sec i will run it right now

**Comment by 0nelight** [comment]
Please change the Boot Stanca for memtest86+ to the following (adjusting to your paths of course):
```
menuentry "MemTest86+" {
	icon /EFI/BOOT/icons/tool_memtest.png
	loader /EFI/TOOLS/memtest64.efi
	options "nobigstatus,nosm,nomch"
}
``` 

[nosm & nomch](https://github.com/memtest86plus/memtest86plus?tab=readme-ov-file#boot-options) could possibly disable some stuff in memtest86+ which the EFI tools are not using to get their memory map.

**Comment by VincePuc99** [comment]
Just finished running the 1st test without nosm&nomch, now in gonna update the refind.conf file according to your new istruction ;)

![IMG_0099](https://github.com/user-attachments/assets/0112428a-3f1f-43e4-9176-fadeeb5111c4)

![IMG_0100](https://github.com/user-attachments/assets/9fccfba9-9c9d-44c0-97e8-8c5971d332b6)

![IMG_0101](https://github.com/user-attachments/assets/9dfb647b-937c-4bce-8e0d-91c7dbe925aa)

![IMG_0102](https://github.com/user-attachments/assets/41d45a9c-384a-41f7-be8d-bffe9b6a9808)

**Comment by 0nelight** [comment]
Thanks! You only need to run it to check whether or not the start of the "Lowest Error Address" gets under 9.50GB -  no need to let it run through.

**Comment by VincePuc99** [comment]
Memtest efi + options

![IMG_0103](https://github.com/user-attachments/assets/740b89a9-4f5a-4f0b-b652-ff8c0bfb3063)

![IMG_0104](https://github.com/user-attachments/assets/709414e8-445e-44c9-b370-653535636a3a)

**Comment by 0nelight** [comment]
Let's don't give up :-) I will think about new things to try out if you still have passion for this?

**Comment by VincePuc99** [comment]
Yesss no problem at all! Lets try it ;)

**Comment by 0nelight** [comment]
Could you please reset the Boot Options to nothing from memtest86+ and then try - instead of the "Error Summary Mode" - the "**Badram**" Mode? Lets check if this modes reports other addresses.

**Comment by 0nelight** [comment]
I really think we have to calculate the virtual address reported by memtest86+ into a physical address which is used by allocpages :-) working on it :-)

**Comment by VincePuc99** [comment]
Trying it right now!

**Comment by VincePuc99** [comment]
Here is the Badram pattern

![IMG_0105](https://github.com/user-attachments/assets/e9e6935a-d121-4e48-ab20-6e9174786de2)
![IMG_0106](https://github.com/user-attachments/assets/e4610544-c3d8-480b-ba09-881fe784768c)
![IMG_0107](https://github.com/user-attachments/assets/619458f4-2b74-4606-a747-2d34656c3fc4)

**Comment by 0nelight** [comment]
I suspect that memtest86+ (no matter what error reporting mode; at least in your case) shows the virtual-address not the physical address - which my EFI-Function allocatepages uses.

I now tried to calculate the real addresses from your information about the 8GB RAM and your memmap.

So these:

Virtual lowest: 0x26380fff0  
Virtual highest: 0x269610630

turn into these:

Phy lowest: 0x1ee80fff1
Phy highest: 0x1f4610631

At least these areas would now be in a realistic area for your macbook - under 8GB.
Could you please check what the program says and if it says Success! run memtest again?

Here the Version with the new Addresses:
[testing-v3-for-VincePuc99.zip](https://github.com/user-attachments/files/16998440/testing-v3-for-VincePuc99.zip)

**Comment by VincePuc99** [comment]
I wanna spend 2 lines talking about you, its incredible seeing how much passion you have in this work! Im so glad i found a nice persone like you ❤️, let solve this problem together!

![IMG_0108](https://github.com/user-attachments/assets/c3ef662d-7f54-41a1-b17a-672f309235e6)

**Comment by 0nelight** [comment]
Two new files to test:
[testing-v4-for-VincePuc99.zip](https://github.com/user-attachments/files/16999589/testing-v4-for-VincePuc99.zip)
[testing-v5-for-VincePuc99.zip](https://github.com/user-attachments/files/16999590/testing-v5-for-VincePuc99.zip)

I made quite a change - I hope both of them will return "Success!" and one of them also will successfully mark the correct area as "Unusable".

**Comment by VincePuc99** [comment]
You are actually INSANE, both tests succeded!!! Look at the GBs on top left of memtest, V4 Failed running V5 right now!

![Immagine WhatsApp 2024-09-14 ore 00 10 21_74e75a66](https://github.com/user-attachments/assets/01d417bd-b0ed-4f27-86ca-6ee7901fe3d1)
V4 Memtest
![Immagine WhatsApp 2024-09-14 ore 00 10 21_4db28307](https://github.com/user-attachments/assets/1953036c-7e37-4314-bc88-69860e5dd04a)
![Immagine WhatsApp 2024-09-14 ore 00 10 20_9c1b9856](https://github.com/user-attachments/assets/3d67e28d-63b0-4525-bd26-aef1324fdf18)

**Comment by VincePuc99** [comment]
V5 PASSED!!!

![Immagine WhatsApp 2024-09-14 ore 00 25 21_1c6852da](https://github.com/user-attachments/assets/4196e319-7d7d-4fa3-8678-36f527bf0b5e)

**Comment by 0nelight** [comment]
😎🥳

**Comment by VincePuc99** [comment]
I hope so 😂😂, thats was a wild ride for sure, but i’m curious, is the script now applicable at every macbook or its still need to be adapted per-person?

**Comment by 0nelight** [comment]
So this version I gave you here (testing-v5) has your specific addresses hardcoded in it. Because I now know what the error is, I will correct the code in the command line version too in the next days. :)

**Comment by JMG444** [comment]
Hello there, sorry if I reopening this. I'm just gonna ask if you please tell me how to you modify the specific addresses that you hardcoded in testing v5. 
Thanks
Sorry if my english isn't well. (If you need specific data or somethin' let me now)

**Comment by 0nelight** [comment]
I will keep this open until I fix it in the main branch.


Aligning to the Previous Page Boundary:
	•	The alignment is done by masking out the lower bits of Addr to align it to the previous page boundary.
	•	This is achieved with:
```
Addr = Addr & ~(EFI_PAGE_SIZE - 1);
```
This operation clears the lower bits of the address, effectively rounding down to the previous 4 KB boundary.

**Comment by 0nelight** [comment]
Fixed with [v0.2.0-beta](https://github.com/0nelight/macOS-Disable-RAM-Areas/releases/tag/v0.2.0-beta) :grin:

**Comment by daniel-nextgti** [comment]
Hello @0nelight ! Once again you`re saving our computers :-)

Thank you so much for all the development and quick replies.

The 4k alignment must be the reason that i had to put a bigger RAM area so MemTest86 dont find any errors.
I`ll try the new 0.2.1 version, but i`m no code expert to 4k align the compiled version (so i could auto-boot with the .nsh).

I`ll be trying myself a little more and post the results later.

**Comment by 0nelight** [comment]
You don't have to take care of the alignment anymore - from now on the Tool itself alignes your input address automatically.

You can directly put in the Values reported from memtest86+ into refind.conf - or into the NSH Script for permanent booting😊

This also make sure as little as necessary of your ram gets disabled, nothing more because the Tool now alignes this automatically to the next lower aligned address. 😊
