### ISSUE TITLE
[Bug] Number of pages is not calculated correctly.

### ISSUE THREAD

**Issue by BrianCArnold** [0nelight/macOS-Disable-RAM-Areas#9]
On line 104, you calculate the number of pages that should be reserved. If there is only a single page affected, the value of NumPages should be `1`, *if I'm reading the docs on the AllocatePages function correctly*.

However, the bit math here makes it pretty easy to end up reserving N-1 pages, leaving the final bad address actually unreserved. 

Here's an example, with the calculations done.

```
EFI_PHYSICAL_ADDRESS Addr = 12287;
EFI_PHYSICAL_ADDRESS EndAddr = 16384;
// EFI_PAGE_SIZE = 4096
Addr = Addr & ~(EFI_PAGE_SIZE - 1); // Addr = 8192
UINTN NumPages = ((16384 - 12287) + EFI_PAGE_SIZE - 1) / EFI_PAGE_SIZE; // NumPages = 2
```

However, the memory locations for each page start at a 4K boundary, and run until, but not including, the next 4K number.

So the first 5 pages are `0-4095`, `4096-8191`, `8192-12287`, `12288-16383`, and `16384-20479`

If we use the resulting values of the code as it stands at the moment, it will allow pages 0 and 1, then mark pages 2 and 3 as bad, and then _**allow**_ page 4, from 16384 - 20479, which we know includes the _end address_.

A better approach is to determine the beginning of the start of the relevant pages, then reduce the addresses to their page number, get the difference, then multiply the starting address by the page size to get our address start.

```
EFI_PHYSICAL_ADDRESS Addr = 12287;
EFI_PHYSICAL_ADDRESS EndAddr = 16384;
Addr /= EFI_PAGE_SIZE; // Integer division, drops the useless bits when we multiply back, and gives us the page number.
EndAddr /= EFI_PAGE_SIZE; // page number for the last address.
UINTN NumPages = EndAddr - Addr + 1; // Gets the difference of the page numbers, and adds one to account for the one we start with.
Addr *= EFI_PAGE_SIZE; // gets us back to addresses, and as a bonus, we're on the page boundary, where we need to be.
Status = uefi_call_wrapper(BS->AllocatePages, 4, 2, 8, NumPages, &Addr);
```

**Comment by 0nelight** [comment]
Nice! Please open a Pull-Request in case you tested you code on a device!
